#include QMK_KEYBOARD_H


/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */


#define _X KC_NO

enum layers {
    DEF,
    SYM,
    NAV,
    NUM,
};

enum keycodes {
    // Custom oneshot mod implementation with no timers.
    OS_SHFT = SAFE_RANGE,
    OS_CTRL,
    OS_ALT,
    OS_GUI,

    SW_WIN,  // Switch to next window         (cmd-tab)
    SW_LANG, // Switch to next input language (ctl-spc)
};

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT(
	_X,       _X,       _X,      _X,    _X,    _X,     _X,       _X,    _X,    _X,    _X, _X,
	_X, KC_QUOT, KC_COMM, KC_DOT, KC_P, KC_Y,     KC_F, KC_G, KC_C, KC_R, KC_L, _X,
	_X, KC_A,    KC_O,    KC_E,   KC_U, KC_I,     KC_D, KC_H, KC_T, KC_N, KC_S, _X,
	_X, KC_SCLN, KC_Q,    KC_J,   KC_K, KC_X, _X, _X, KC_B, KC_M, KC_W, KC_V, KC_Z, _X,
	_X, _X, MO(2), KC_LSFT, MO(2),                 MO(1), KC_SPC, MO(1), _X, _X),
	[1] = LAYOUT(
	_X, _X, _X, _X, _X, _X,                                  _X, _X, _X, _X, _X, _X,
	_X, KC_ESC, KC_LBRC, KC_LCBR, KC_LPRN, KC_TILD,     KC_CIRC, KC_RPRN, KC_RCBR, KC_RBRC, KC_GRV, _X,
	_X, KC_MINS, KC_ASTR, KC_EQL, KC_UNDS, KC_DLR,      KC_HASH, OS_GUI, OS_ALT, OS_CTRL, OS_SHFT, _X,
	_X, KC_PLUS, KC_PIPE, KC_AT, KC_SLSH, KC_PERC, _X,  _X, _X, KC_BSLS, KC_AMPR, KC_QUES, KC_EXLM, _X,
	_X, _X, KC_TRNS, KC_TRNS, KC_TRNS,                       KC_TRNS, KC_TRNS, KC_TRNS, _X, _X),
	[2] = LAYOUT(
	_X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X,
	_X, KC_TAB, _X, _X, _X, KC_VOLU, _X, KC_HOME, KC_UP, KC_END, KC_DEL, _X,
	_X, OS_SHFT, OS_CTRL, OS_ALT, OS_GUI, KC_VOLD,   _X, KC_LEFT, KC_DOWN, KC_RGHT, KC_BSPC, _X,
	_X, _X, _X, KC_MRWD, KC_MFFD, KC_MPLY, _X,     _X, _X, KC_PGDN, KC_PGUP, _X, KC_ENT, _X,
	_X, _X, KC_TRNS, KC_TRNS, KC_TRNS,           KC_TRNS, KC_TRNS, KC_TRNS, _X, _X),
	[3] = LAYOUT(
	_X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X,
	_X, KC_7, KC_5, KC_3, KC_1, KC_9,      KC_8, KC_0, KC_2, KC_4, KC_6, _X,
	_X, OS_SHFT, OS_CTRL, OS_ALT, OS_GUI, KC_F11,    KC_F10, OS_GUI, OS_ALT, OS_CTRL, OS_SHFT, _X,
	_X, KC_F7, KC_F5, KC_F3, KC_F1, KC_F9, _X,        _X, KC_F8, KC_F12, KC_F2, KC_F4, KC_F6, _X,
	_X, _X, KC_TRNS, KC_TRNS, KC_TRNS,                KC_TRNS, KC_TRNS, KC_TRNS, _X, _X),
	[4] = LAYOUT(
	_X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, KC_MPLY, KC_MSTP, KC_MUTE, KC_MNXT, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X),
	[5] = LAYOUT(
	_X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, QK_BOOT, EE_CLR, _X, _X, _X, _X, DT_PRNT, DT_UP, DT_DOWN, _X, _X, _X, RGB_TOG, RGB_MOD, RGB_VAD, RGB_VAI, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, _X, KC_TRNS, _X, _X, _X, _X, _X, _X, KC_TRNS, _X)
};

layer_state_t layer_state_set_user(layer_state_t state) {
    return update_tri_layer_state(state, SYM, NAV, NUM);
}

#if defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {

};
#endif // defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)





