OLED_ENABLE = yes
ENCODER_ENABLE = yes
EXTRAKEY_ENABLE = yes
MOUSEKEY_ENABLE = yes
RGBLIGHT_ENABLE = yes
LTO_ENABLE = yes

DYNAMIC_TAPPING_TERM_ENABLE = yes

CONSOLE_ENABLE = no

SRC += oled.c encoder.c
