OLED_ENABLE = yes
ENCODER_ENABLE = yes
EXTRAKEY_ENABLE = yes
MOUSEKEY_ENABLE = no
RGBLIGHT_ENABLE = yes
LTO_ENABLE = yes

DYNAMIC_TAPPING_TERM_ENABLE = yes
SLEEP_LED_ENABLE = no
NKRO_ENABLE = no
CONSOLE_ENABLE = no

SRC += oled.c encoder.c
